sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rwedwards/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rwedwards/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-975050048631"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY